services:
  postgres:
    image: postgres:17-alpine
    env_file:
      - .env.development.database
    ports:
      - "5433:5432"
    volumes:
      - tech-test-front_pg_data:/var/lib/postgresql/data

volumes:
  tech-test-front_pg_data:
